export const clients = [
  { name: 'Anglerfox', logo: '/clients/anglerfox.png' },
  { name: 'Annular Technologies', logo: '/clients/annular-technologies.png' },
  { name: 'BranchX', logo: '/clients/branchx.png' },
  { name: 'Cateina', logo: '/clients/cateina.png' },
  { name: 'Codersbrain', logo: '/clients/codersbrain.png' },
  { name: 'Discreet', logo: '/clients/discreet.png' },
  { name: 'Enlign', logo: '/clients/enlign.png' },
  { name: 'Jainfoway', logo: '/clients/jainfoway.png' },
  { name: 'MW', logo: '/clients/mw.png' },
  { name: 'Nihon Technology', logo: '/clients/nihon-technology.png' },
  { name: 'Nihon', logo: '/clients/nihon.png' },
  { name: 'Oasys', logo: '/clients/oasys.png' },
  { name: 'Recro', logo: '/clients/recro.png' },
  { name: 'Revalsys', logo: '/clients/revalsys.png' },
  { name: 'Splenta', logo: '/clients/splenta.png' },
  { name: 'Step To Soft', logo: '/clients/step-to-soft.png' },
  { name: 'Tailwebs', logo: '/clients/tailwebs.png' },
];
