import { Code, Smartphone, BrainCircuit, Target, Users, BarChart2, Globe, Cloud, PenTool, Cpu, Shield, Megaphone, GitMerge, Bitcoin, Building, Plug, ClipboardCheck, Briefcase, PieChart, Router, History, Layers, AppWindow, Database } from 'lucide-react';
import type { Service, Insight, TeamMember, Client, MediaMention, Project, CaseStudy } from './types';
import { placeholderImages } from './image-map';

export const services: Service[] = [
  {
    id: 'web-development',
    title: 'Web Development',
    description: 'Custom websites, e-commerce, CMS platforms.',
    longDescription: 'We build beautiful and intuitive web and mobile applications that captivate users and deliver exceptional experiences. Our team leverages the latest technologies to create cross-platform apps that are fast, reliable, and easy to use. Whether it\'s a consumer-facing app or an internal business tool, we have you covered.',
    icon: Globe,
    href: '/services/web-development',
    imageUrl: placeholderImages.heroWebDev.imageUrl,
    imageHint: placeholderImages.heroWebDev.imageHint,
  },
  {
    id: 'mobile-app-development',
    title: 'Mobile App Development',
    description: 'Android, iOS, and cross-platform mobile applications.',
    longDescription: 'We build beautiful and intuitive web and mobile applications that captivate users and deliver exceptional experiences. Our team leverages the latest technologies to create cross-platform apps that are fast, reliable, and easy to use. Whether it\'s a consumer-facing app or an internal business tool, we have you covered.',
    icon: Smartphone,
    href: '/services/mobile-app-development',
    imageUrl: placeholderImages.heroMobileDev.imageUrl,
    imageHint: placeholderImages.heroMobileDev.imageHint,
  },
  {
    id: 'cloud-services',
    title: 'Cloud Services',
    description: 'Cloud computing, storage, and migration solutions.',
    longDescription: 'Harness the power of the cloud with our comprehensive cloud services. We offer cloud strategy, migration, and management services to help you build a scalable and resilient infrastructure. Our expertise spans across major cloud platforms, including AWS, Azure, and Google Cloud.',
    icon: Cloud,
    href: '/services/cloud-services',
    imageUrl: placeholderImages.heroCloud.imageUrl,
    imageHint: placeholderImages.heroCloud.imageHint,
  },
  {
    id: 'ui-ux-design',
    title: 'UI/UX Design',
    description: 'User interface and user experience design for websites and apps.',
    longDescription: 'Great software is more than just code; it\'s about creating a seamless and intuitive user experience. Our UI/UX design team works to understand your users and design interfaces that are not only beautiful but also easy to use and navigate.',
    icon: PenTool,
    href: '/services/ui-ux-design',
    imageUrl: placeholderImages.insight3.imageUrl,
    imageHint: placeholderImages.insight3.imageHint,
  },
  {
    id: 'artificial-intelligence-machine-learning',
    title: 'Artificial Intelligence & Machine Learning',
    description: 'AI tools, chatbots, and predictive analytics.',
    longDescription: 'Harness the power of Artificial Intelligence with our custom AI and machine learning solutions. We help businesses automate complex processes, gain valuable insights from data, and create intelligent products. From natural language processing to predictive analytics, we build AI-driven systems that deliver tangible results.',
    icon: Cpu,
    href: '/services/artificial-intelligence-machine-learning',
    imageUrl: placeholderImages.insight1.imageUrl,
    imageHint: placeholderImages.insight1.imageHint,
  },
  {
    id: 'cybersecurity',
    title: 'Cybersecurity',
    description: 'Data protection, security audits, and threat prevention.',
    longDescription: 'In an increasingly digital world, security is paramount. Our cybersecurity services are designed to protect your data and infrastructure from evolving threats. We offer security audits, penetration testing, and a range of other services to help you stay ahead of the curve.',
    icon: Shield,
    href: '/services/cybersecurity',
    imageUrl: placeholderImages.project1.imageUrl,
    imageHint: placeholderImages.project1.imageHint,
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing',
    description: 'SEO, social media marketing, and content strategies.',
    longDescription: 'Your product is only as good as your ability to reach your target audience. Our digital marketing services can help you connect with your customers and grow your business. We offer a range of services, including SEO, social media marketing, and content strategy.',
    icon: Megaphone,
    href: '/services/digital-marketing',
    imageUrl: placeholderImages.heroMedia.imageUrl,
    imageHint: placeholderImages.heroMedia.imageHint,
  },
  {
    id: 'devops-services',
    title: 'DevOps Services',
    description: 'CI/CD pipelines, infrastructure as code, and containerization.',
    longDescription: 'Streamline your development process and accelerate your time to market with our DevOps services. We can help you implement CI/CD pipelines, automate your infrastructure, and leverage containerization technologies like Docker and Kubernetes.',
    icon: GitMerge,
    href: '/services/devops-services',
    imageUrl: placeholderImages.insight6.imageUrl,
    imageHint: placeholderImages.insight6.imageHint,
  },
  {
    id: 'blockchain-solutions',
    title: 'Blockchain Solutions',
    description: 'Decentralized applications, smart contracts, and cryptocurrency platforms.',
    longDescription: 'Explore the potential of blockchain technology with our custom blockchain solutions. We can help you build decentralized applications, smart contracts, and cryptocurrency platforms that are secure, transparent, and immutable.',
    icon: Bitcoin,
    href: '/services/blockchain-solutions',
    imageUrl: placeholderImages.heroVentureCapital.imageUrl,
    imageHint: placeholderImages.heroVentureCapital.imageHint,
  },
  {
    id: 'enterprise-software-development',
    title: 'Enterprise Software Development',
    description: 'Large-scale software solutions for enterprise environments.',
    longDescription: 'We specialize in building robust and scalable software solutions for large enterprises. Our team has the expertise to tackle complex challenges and deliver software that meets the demands of a modern enterprise environment.',
    icon: Building,
    href: '/services/enterprise-software-development',
    imageUrl: placeholderImages.heroAbout.imageUrl,
    imageHint: placeholderImages.heroAbout.imageHint,
  },
  {
    id: 'api-development-and-integration',
    title: 'API Development and Integration',
    description: 'Connecting your software systems and enabling new capabilities.',
    longDescription: 'Our API development and integration services can help you unlock new capabilities and create a more connected software ecosystem. We design and build APIs that are secure, scalable, and easy to use.',
    icon: Plug,
    href: '/services/api-development-and-integration',
    imageUrl: placeholderImages.insight2.imageUrl,
    imageHint: placeholderImages.insight2.imageHint,
  },
  {
    id: 'quality-assurance-and-testing',
    title: 'Quality Assurance and Testing',
    description: 'Ensuring your software is reliable, secure, and performant.',
    longDescription: 'Our quality assurance and testing services are designed to give you confidence in your software. We offer a range of testing services, including functional testing, performance testing, and security testing.',
    icon: ClipboardCheck,
    href: '/services/quality-assurance-and-testing',
    imageUrl: placeholderImages.heroContact.imageUrl,
    imageHint: placeholderImages.heroContact.imageHint,
  },
  {
    id: 'it-consulting-and-strategy',
    title: 'IT Consulting and Strategy',
    description: 'Expert guidance to help you navigate the ever-changing technology landscape.',
    longDescription: 'Our IT consulting and strategy services can help you make the right technology decisions for your business. We provide expert guidance on everything from technology selection to digital transformation.',
    icon: Briefcase,
    href: '/services/it-consulting-and-strategy',
    imageUrl: placeholderImages.teamMember1.imageUrl,
    imageHint: placeholderImages.teamMember1.imageHint,
  },
  {
    id: 'data-analytics-and-business-intelligence',
    title: 'Data Analytics and Business Intelligence',
    description: 'Turning your data into actionable insights.',
    longDescription: 'Unlock the power of your data with our data analytics and business intelligence services. We can help you collect, analyze, and visualize your data to gain valuable insights and make better business decisions.',
    icon: PieChart,
    href: '/services/data-analytics-and-business-intelligence',
    imageUrl: placeholderImages.heroEquityMarkets.imageUrl,
    imageHint: placeholderImages.heroEquityMarkets.imageHint,
  },
  {
    id: 'internet-of-things-iot-development',
    title: 'Internet of Things (IoT) Development',
    description: 'Connecting the physical and digital worlds.',
    longDescription: 'Our IoT development services can help you create innovative products and services that connect the physical and digital worlds. We have the expertise to build everything from smart home devices to industrial IoT solutions.',
    icon: Router,
    href: '/services/internet-of-things-iot-development',
    imageUrl: placeholderImages.insight5.imageUrl,
    imageHint: placeholderImages.insight5.imageHint,
  },
  {
    id: 'legacy-system-modernization',
    title: 'Legacy System Modernization',
    description: 'Bringing your old software systems into the modern era.',
    longDescription: 'Don\'t let your legacy systems hold you back. Our legacy system modernization services can help you update your old software systems to take advantage of modern technologies and improve performance, security, and scalability.',
    icon: History,
    href: '/services/legacy-system-modernization',
    imageUrl: placeholderImages.project3.imageUrl,
    imageHint: placeholderImages.project3.imageHint,
  },
  {
    id: 'full-stack-development',
    title: 'Full Stack Development',
    description: 'End-to-end development of your web and mobile applications.',
    longDescription: 'Our full stack development services cover everything from the front-end to the back-end, ensuring a seamless and integrated solution. We have the expertise to build complex applications from the ground up.',
    icon: Layers,
    href: '/services/full-stack-development',
    imageUrl: placeholderImages.insight2.imageUrl,
    imageHint: placeholderImages.insight2.imageHint,
  },
  {
    id: 'frontend-development',
    title: 'Frontend Development',
    description: 'Creating beautiful and intuitive user interfaces.',
    longDescription: 'Our front-end development team specializes in creating user interfaces that are not only visually appealing but also highly functional and easy to use. We leverage the latest front-end technologies to build experiences that your users will love.',
    icon: AppWindow,
    href: '/services/frontend-development',
    imageUrl: placeholderImages.heroWebDev.imageUrl,
    imageHint: placeholderImages.heroWebDev.imageHint,
  },
  {
    id: 'backend-development',
    title: 'Backend Development',
    description: 'Building the robust and scalable foundation for your applications.',
    longDescription: 'Our back-end development services provide the foundation for your applications. We build robust and scalable back-end systems that can handle high traffic and complex business logic.',
    icon: Database,
    href: '/services/backend-development',
    imageUrl: placeholderImages.project1.imageUrl,
    imageHint: placeholderImages.project1.imageHint,
  },
];

export const investmentApproach = [
    {
      title: "Agile Development",
      description: "Our iterative approach ensures we can adapt to changing requirements and deliver value quickly and efficiently.",
      icon: Target,
    },
    {
      title: "User-Centric Design",
      description: "We place users at the center of our design process, creating intuitive and engaging experiences.",
      icon: Users,
    },
    {
      title: "Scalable Architecture",
      description: "We build robust and scalable systems that can grow with your business and handle increasing demand.",
      icon: BarChart2,
    },
    {
      title: "Cutting-Edge Technology",
      description: "We stay at the forefront of technology to deliver modern, high-performance solutions.",
      icon: BrainCircuit,
    },
]

export const insights: Insight[] = [
  {
    id: '1',
    title: 'The Future of AI in FinTech: A 2024 Perspective',
    description: 'An in-depth analysis of how artificial intelligence is reshaping the financial technology landscape, from automated trading to personalized banking.',
    imageUrl: placeholderImages.insight1.imageUrl,
    imageHint: placeholderImages.insight1.imageHint,
    category: 'AI & Machine Learning',
    date: 'August 15, 2024',
  },
  {
    id: '2',
    title: 'Building Scalable Web Apps with Next.js',
    description: 'Exploring the advantages of using Next.js for modern web development and best practices for building scalable applications.',
    imageUrl: placeholderImages.insight2.imageUrl,
    imageHint: placeholderImages.insight2.imageHint,
    category: 'Web Development',
    date: 'July 28, 2024',
  },
  {
    id: '3',
    title: 'The Importance of UX in Enterprise Software',
    description: 'A look into why user experience is critical for the success of enterprise applications and how to design for usability.',
    imageUrl: placeholderImages.insight3.imageUrl,
    imageHint: placeholderImages.insight3.imageHint,
    category: 'UX Design',
    date: 'July 10, 2024',
  },
  {
    id: '4',
    title: 'The Metaverse: Hype vs. Reality for Enterprise',
    description: 'Cutting through the noise to identify real-world enterprise applications and investment theses for the metaverse.',
    imageUrl: placeholderImages.insight4.imageUrl,
    imageHint: placeholderImages.insight4.imageHint,
    category: 'Future Tech',
    date: 'June 22, 2024',
  },
  {
    id: '5',
    title: 'AI-Powered Summarization: A Case Study',
    description: 'An overview of how we built an AI-powered text summarization tool and the challenges we overcame.',
    imageUrl: placeholderImages.insight5.imageUrl,
    imageHint: placeholderImages.insight5.imageHint,
    category: 'AI Solutions',
    date: 'June 5, 2024',
  },
  {
    id: '6',
    title: 'Choosing the Right Tech Stack for Your Mobile App',
    description: 'A guide to help you decide on the best technology stack for your mobile application based on your needs and goals.',
    imageUrl: placeholderImages.insight6.imageUrl,
    imageHint: placeholderImages.insight6.imageHint,
    category: 'Mobile Development',
    date: 'May 21, 2024',
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Eleanor Vance',
    role: 'CEO & Founder',
    imageUrl: placeholderImages.teamMember1.imageUrl,
    imageHint: placeholderImages.teamMember1.imageHint,
  },
  {
    id: '2',
    name: 'Marcus Thorne',
    role: 'CTO',
    imageUrl: placeholderImages.teamMember2.imageUrl,
    imageHint: placeholderImages.teamMember2.imageHint,
  },
  {
    id: '3',
    name: 'Isabelle Rossi',
    role: 'Head of Product',
    imageUrl: placeholderImages.teamMember3.imageUrl,
    imageHint: placeholderImages.teamMember3.imageHint,
  },
  {
    id: '4',
    name: 'Julian Chen',
    role: 'Lead Engineer',
    imageUrl: placeholderImages.teamMember4.imageUrl,
    imageHint: placeholderImages.teamMember4.imageHint,
  },
];

export const clients: Client[] = [
    { id: '1', name: "InnovateAI", logoUrl: placeholderImages.portfolioLogo1.imageUrl, logoHint: placeholderImages.portfolioLogo1.imageHint },
    { id: '2', name: "QuantumLeap", logoUrl: placeholderImages.portfolioLogo2.imageUrl, logoHint: placeholderImages.portfolioLogo2.imageHint },
    { id: '3', name: "BioGenex", logoUrl: placeholderImages.portfolioLogo3.imageUrl, logoHint: placeholderImages.portfolioLogo3.imageHint },
    { id: '4', name: "FutureSynth", logoUrl: placeholderImages.portfolioLogo4.imageUrl, logoHint: placeholderImages.portfolioLogo4.imageHint },
    { id: '5', name: "NextGen Mobility", logoUrl: placeholderImages.portfolioLogo5.imageUrl, logoHint: placeholderImages.portfolioLogo5.imageHint },
    { id: '6', name: "DataWeave", logoUrl: placeholderImages.portfolioLogo6.imageUrl, logoHint: placeholderImages.portfolioLogo6.imageHint },
    { id: '7', name: "Nihon Technology", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/nihon.png", logoHint: "Nihon Technology Logo" },
    { id: '8', name: "Recro", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/recro.png", logoHint: "Recro Logo" },
    { id: '9', name: "Enliven", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/enliven.png", logoHint: "Enliven Logo" },
    { id: '10', name: "MV", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/mv.png", logoHint: "MV Logo" },
    { id: '11', name: "IA InFoway", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/ia-infoway.png", logoHint: "IA InFoway Logo" },
    { id: '12', name: "Annular Technologies", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/annular.png", logoHint: "Annular Technologies Logo" },
    { id: '13', name: "AnglerFox", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/anglerfox.png", logoHint: "AnglerFox Logo" },
    { id: '14', name: "Cateina", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/cateina.png", logoHint: "Cateina Logo" },
    { id: '15', name: "BranchX", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/branchx.png", logoHint: "BranchX Logo" },
    { id: '16', name: "Revalsys", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/revalsys.png", logoHint: "Revalsys Logo" },
    { id: '17', name: "Oasys", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/oasys.png", logoHint: "Oasys Logo" },
    { id: '18', name: "Splenta", logoUrl: "https://whitewhalesoft.in/wp-content.uploads/2023/07/splenta.png", logoHint: "Splenta Logo" },
    { id: '19', name: "Tailwebs", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/tailwebs.png", logoHint: "Tailwebs Logo" },
    { id: '20', name: "Discreet", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/discreet.png", logoHint: "Discreet Logo" },
    { id: '21', name: "Step to Soft", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/step-to-soft.png", logoHint: "Step to Soft Logo" },
    { id: '22', name: "CodersBrain", logoUrl: "https://whitewhalesoft.in/wp-content/uploads/2023/07/codersbrain.png", logoHint: "CodersBrain Logo" },
]

export const mediaMentions: MediaMention[] = [
    {
        id: '1',
        title: 'Case Study: How We Boosted E-commerce Sales by 300%',
        publication: 'Client: Retailify',
        date: 'August 1, 2024',
        link: '#',
        imageUrl: placeholderImages.mediaPublication1.imageUrl,
        imageHint: placeholderImages.mediaPublication1.imageHint,
    },
    {
        id: '2',
        title: 'Building a Scalable AI Platform for a FinTech Leader',
        publication: 'Client: FinSecure',
        date: 'July 20, 2024',
        link: '#',
        imageUrl: placeholderImages.mediaPublication2.imageUrl,
        imageHint: placeholderImages.mediaPublication2.imageHint,
    },
    {
        id: '3',
        title: 'Developing a Cross-Platform Mobile App for Healthcare',
        publication: 'Client: HealthSphere',
        date: 'July 5, 2024',
        link: '#',
        imageUrl: placeholderImages.mediaPublication3.imageUrl,
        imageHint: placeholderImages.mediaPublication3.imageHint,
    }
]

export const projects: Project[] = [
  {
    id: '1',
    name: 'E-commerce Platform',
    description: 'A feature-rich online store with a custom CMS and payment gateway integration.',
    imageUrl: placeholderImages.project3.imageUrl,
    imageHint: placeholderImages.project3.imageHint,
    category: 'E-commerce',
  },
  {
    id: '2',
    name: 'FinTech Mobile App',
    description: 'An iOS and Android app for personal finance management and investment tracking.',
    imageUrl: placeholderImages.project2.imageUrl,
    imageHint: placeholderImages.project2.imageHint,
    category: 'FinTech',
  },
  {
    id: '3',
    name: 'AI-Powered Analytics Dashboard',
    description: 'A web-based platform that uses machine learning to provide business intelligence.',
    imageUrl: placeholderImages.project1.imageUrl,
    imageHint: placeholderImages.project1.imageHint,
    category: 'AI & Machine Learning',
  },
  {
    id: '4',
    name: 'Healthcare Management System',
    description: 'A comprehensive software solution for hospitals and clinics.',
    imageUrl: placeholderImages.heroMobileDev.imageUrl, // Placeholder
    imageHint: 'healthcare management system',
    category: 'Healthcare',
  },
  {
    id: '5',
    name: 'Education Tech Platform',
    description: 'An online learning platform with interactive courses and a student management system.',
    imageUrl: placeholderImages.insight3.imageUrl, // Placeholder
    imageHint: 'education tech platform',
    category: 'Education Tech',
  },
  {
    id: '6',
    name: 'Real Estate Portal',
    description: 'A web and mobile platform for property listings, virtual tours, and agent management.',
    imageUrl: placeholderImages.heroAbout.imageUrl, // Placeholder
    imageHint: 'real estate portal',
    category: 'Real Estate',
  }
];

export const caseStudies: CaseStudy[] = [
  {
    id: "e-commerce-boost",
    title: "Boosting E-commerce Sales by 300% for Retailify",
    client: "Retailify",
    description: "A comprehensive overhaul of Retailify's online presence, leading to a massive increase in sales and customer engagement.",
    challenge: "Retailify's existing e-commerce platform was outdated, slow, and not mobile-friendly. They were losing customers and revenue due to a poor user experience.",
    solution: "We designed and developed a new, modern e-commerce platform from the ground up using Next.js and Shopify. The new site is fast, responsive, and features a streamlined checkout process. We also implemented a new SEO strategy to improve their search engine rankings.",
    results: [
      "300% increase in online sales within 6 months.",
      "50% reduction in page load times.",
      "40% increase in mobile conversion rates.",
      "Top 3 ranking on Google for key product categories."
    ],
    imageUrl: placeholderImages.project3.imageUrl
  },
  {
    id: "fintech-ai-platform",
    title: "Building a Scalable AI Platform for FinSecure",
    client: "FinSecure",
    description: "Delivering a cutting-edge AI platform for a leading FinTech company to enhance their fraud detection capabilities.",
    challenge: "FinSecure needed to improve the accuracy and speed of their fraud detection system to combat increasingly sophisticated fraudulent activities.",
    solution: "Our team developed a real-time AI-powered fraud detection platform using machine learning models. The system analyzes transaction data in real-time to identify and flag suspicious activities, significantly reducing false positives and improving detection rates.",
    results: [
      "95% accuracy in fraud detection.",
      "Reduced false positives by 60%.",
      "Real-time processing of over 10,000 transactions per second.",
      "Enhanced security and trust for millions of users."
    ],
    imageUrl: placeholderImages.project1.imageUrl
  },
  {
    id: "healthcare-mobile-app",
    title: "Cross-Platform Mobile App for HealthSphere",
    client: "HealthSphere",
    description: "Creating an intuitive mobile app to help patients manage their health records and appointments.",
    challenge: "HealthSphere wanted to provide their patients with a convenient way to access their health information, book appointments, and communicate with their doctors. They needed a secure and user-friendly app that worked on both iOS and Android.",
    solution: "We developed a cross-platform mobile app using React Native that allows patients to securely access their medical records, schedule appointments, and communicate with their healthcare providers. The app integrates with their existing EHR system and features a clean, intuitive interface.",
    results: [
      "Over 100,000 downloads in the first year.",
      "Improved patient engagement and satisfaction.",
      "Streamlined appointment booking process, reducing administrative overhead.",
      "Secure and HIPAA-compliant data handling."
    ],
    imageUrl: placeholderImages.heroMobileDev.imageUrl
  }
];
